FROM nginx:mainline-alpine-slim

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

# 添加别名 方便看日志
RUN echo -e '#!/bin/sh\ntail -f /var/log/nginx/vitamin.log' > /usr/bin/vitamin && \
    chmod 777 /usr/bin/vitamin

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
