#!/bin/bash

# 该脚本用于 hexo个人博客 的各种操作

if [ $# -lt 1 ]
then
  echo Not Enough Argument!
  exit;
fi

cd $HOME/Documents/lkzc19.github.io
if [ "$1" == "s" ]; then
  hexo clean
  hexo g
  hexo server  
elif [ "$1" == "d" ]; then
	hexo clean
	hexo g
  hexo d 
elif [ "$1" == "sync" ]; then
  git checkout main
	git pull origin main
  git add .
  git commit -m "sync"
  git push
else
  echo "参数错误 参考以下："
	echo "  s     本地部署"
  echo "	d     部署博客"
  echo "	sync  同步代码"
fi


