FROM bitnami/openresty:1.25-debian-12

ENV TZ=Asia/Shanghai

COPY default.conf /opt/bitnami/openresty/nginx/conf/server_blocks/default.conf

EXPOSE 3000

ENTRYPOINT ["/opt/bitnami/scripts/openresty/run.sh"]
