version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: vitamin
      POSTGRES_USER: vitamin
      POSTGRES_PASSWORD: vitamin
    ports:
      - "3432:5432"