// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"wirez/repo"
	"wirez/service"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	pgsqlStr, cleanup, err := initPgsql(ctx)
	if err != nil {
		return nil, nil, err
	}
	mongoStr, cleanup2, err := initMongo(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fooRepo := repo.ProvideFooRepo(pgsqlStr)
	fooService := service.FooService{
		FooRepo: fooRepo,
	}
	s := S{
		FooService: fooService,
	}
	injector := &Injector{
		Pgsql: pgsqlStr,
		Mongo: mongoStr,
		S:     s,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
