// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"wirez/repo"
	"wirez/service"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	pgsqlStr, cleanup, err := initPgsql(ctx)
	if err != nil {
		return nil, nil, err
	}
	mongoStr, cleanup2, err := initMongo(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dbStr, cleanup3, err := initDB(pgsqlStr, mongoStr)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sussurro, err := initSussurro()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fooRepo := repo.ProvideFooRepo(pgsqlStr)
	barRepo := repo.ProvideBarRepo()
	helloService := service.HelloService{
		FooRepo: fooRepo,
		BarRepo: barRepo,
	}
	s := S{
		FooService: helloService,
	}
	injector := &Injector{
		Pgsql:    pgsqlStr,
		Mongo:    mongoStr,
		DB:       dbStr,
		Sussurro: sussurro,
		S:        s,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
