
server:
  port: 3000

spring:
  application:
    name: v-mybatis
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vitamin
    username: vitamin
    password: vitamin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl