// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"wirez/repo"
	"wirez/service"
	"wirez/wirex/provider"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	pgsqlStr, cleanup, err := provider.Pgsql(ctx)
	if err != nil {
		return nil, nil, err
	}
	mongoStr, cleanup2, err := provider.Mongo(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dbStr, cleanup3, err := provider.DB(pgsqlStr, mongoStr)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sussurro, err := provider.Sussurro()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fooRepo := repo.ProvideFooRepo(pgsqlStr)
	barRepo := repo.ProvideBarRepo(pgsqlStr)
	bar2Repo := repo.ProvideBar2Repo(pgsqlStr)
	helloService := service.HelloService{
		FooRepo:  fooRepo,
		BarRepo:  barRepo,
		Bar2Repo: bar2Repo,
	}
	s := S{
		FooService: helloService,
	}
	injector := &Injector{
		Pgsql:    pgsqlStr,
		Mongo:    mongoStr,
		DB:       dbStr,
		Sussurro: sussurro,
		S:        s,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
