global:
  resolve_timeout: 5m
  smtp_from: 'drinkice_cat@foxmail.com'
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_auth_username: 'drinkice_cat@foxmail.com'
  smtp_auth_password: 'xxxxxxxxxxxxx'
  smtp_require_tls: false
  smtp_hello: 'qq.com'
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'xxxxxxxxxxxx'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']