global:
  scrape_interval: 10s # short interval for manual testing

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: "java-example"
    static_configs:
      - targets: ["host.docker.internal:9400"]