version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: vitamin
      POSTGRES_USER: vitamin
      POSTGRES_PASSWORD: vitamin
    ports:
      - 5432:5432
