server:
  port: 3000

spring:
  application:
    name: v-jimmer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3306/jimmer_demo
    username: vitamin
    password: vitamin

jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR