# 平时写demo使用的Redis
version: '3'

services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql-8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: ry-vue
    ports:
      - "3306:3306"
    volumes:
      - ruoyi_mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  ruoyi_mysql_data: