spring:
  application:
    name: v-mail
  mail:
    host: smtp.qq.com
    username: drinkice_cat@foxmail.com
    password: ifwxrywhocoyebjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true