server:
  port: 3000

spring:
  application:
    name: v-mybatis
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 111111
mybatis:
  typeAliasesPackage: org.example.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true