FROM nginx

ENV TZ=Asia/Shanghai

RUN apt-get update && apt-get install -y gnupg2 curl
RUN echo "deb http://nginx.org/packages/mainline/debian/ buster nginx" >> /etc/apt/sources.list \
    && curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add - \
    && apt-get update \
    && apt-get install -y libnginx-mod-http-lua lua-cjson

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY lua-scripts /etc/nginx/lua-scripts

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
