FROM nginx:stable-bookworm

ENV TZ=Asia/Shanghai

# RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
# RUN sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
# RUN apt-get update && apt-get upgrade -y
# RUN apt-get install -y libnginx-mod-http-lua lua-cjson


    # RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    # && sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list \
    # && apt-get update && apt-get upgrade -y \
    # && apt-get install -y libnginx-mod-http-lua lua-cjson

# RUN apt-get update && apt-get install -y gnupg2 curl
# RUN echo "deb http://nginx.org/packages/mainline/debian/ buster nginx" >> /etc/apt/sources.list \
#     && curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add - \
#     && apt-get update \
#     && apt-get install -y libnginx-mod-http-lua lua-cjson

COPY nginx.conf /etc/nginx/nginx.conf
# COPY default.conf /etc/nginx/conf.d/default.conf
COPY lua-scripts /etc/nginx/lua-scripts

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
