FROM nginx:stable-bookworm

ENV TZ=Asia/Shanghai

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
# COPY lua-scripts /etc/nginx/lua-scripts

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
