server:
  port: 3000

spring:
  application:
    name: sso-spring
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: trace