# https://docs.nats.io/running-a-nats-service/nats_docker
version: "3.5"

services:
  nats-0:
    image: nats
    ports:
      - "3228:8222"
      - "3226:6222"
      - "3224:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-0:6222"
    networks: ["nats"]
    depends_on: ["nats-0"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-0:6222"
    networks: ["nats"]
    depends_on: ["nats-0"]

networks:
  nats:
    name: nats
