version: '3'

services:
  pgsql:
    image: postgres:11.21-alpine3.18
    container_name: pgsql-11x
    restart: always
    environment:
      POSTGRES_PASSWORD: vitamin
    volumes:
      - ./data-11x:/var/lib/postgresql/data
    ports:
      - 5433:5432
