version: '3'

services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    environment:
      # MYSQL_DATABASE: book
      MYSQL_ROOT_PASSWORD: zxczxc
      # MYSQL_DEFAULT_CHARACTER_SET: utf8mb4
      # MYSQL_DEFAULT_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - $HOME/dev/mysql:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: zxczxc
    ports:
      - 9432:9432
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - vitamin
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9092:9092
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
  # === 普罗米修斯 相关 ===
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./prometheus/example.rules:/opt/bitnami/prometheus/conf/rules/example.rules
      - '$HOME/dev/prometheus/data:/opt/bitnami/prometheus/data'
  pushgateway:
    image: bitnami/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
  alertmanager:
    image: bitnami/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml
    ports:
      - "9093:9093"
  # === 普罗米修斯 相关 ===



networks:
  vitamin:
    driver: bridge