version: '3'

services:
  pgsql:
    image: postgres
    container_name: v-pgsql
    restart: always
    environment:
      POSTGRES_DB: vitamin
      POSTGRES_USER: vitamin
      POSTGRES_PASSWORD: vitamin
    ports:
      - 3432:5432
    networks:
      - vitamin
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: v-kafka
    networks:
      - vitamin
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9092:9092
      - 9094:9094

  namenode:
    image: apache/hadoop:3
    container_name: v-hadoop-namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    image: apache/hadoop:3
    container_name: v-hadoop-datanode
    command: ["hdfs", "datanode"]
    env_file:
      - ./config      
  resourcemanager:
    image: apache/hadoop:3
    container_name: v-hadoop-resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
       - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:3
    container_name: v-hadoop-nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  spark:
    image: docker.io/bitnami/spark:3.5
    container_name: v-spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    networks:
      - vitamin
  spark-worker:
    image: docker.io/bitnami/spark:3.5
    container_name: v-spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://vitamin:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - vitamin

networks:
  vitamin:
    driver: bridge