# 平时写demo使用的Redis
version: '3'

services:
  pgsql:
    image: postgres
    container_name: v-pgsql
    restart: always
    environment:
      POSTGRES_DB: vitamin
      POSTGRES_USER: vitamin
      POSTGRES_PASSWORD: vitamin
    ports:
      - 3432:5432
