server:
  port: 3000

spring:
  application:
    name: spring-jpa
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3432/vitamin
    username: vitamin
    password: vitamin
  jpa:
    database: postgresql
    show-sql: true

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl