name: ci-cache-node

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-poc/ci/cache-node/**'

env:
  WORKSPACE: 'v-poc/ci/cache-node'

jobs:
  ci-cache-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Restore
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.WORKSPACE }}/node_modules
            ${{ env.WORKSPACE }}/.nuxt
          key: ci-cache-node-${{ hashFiles('v-poc/ci/cache-node/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ${{ env.WORKSPACE }}
          npm install
      - name: Build
        run: |
          cd ${{ env.WORKSPACE }}
          npm run build
      - name: Save
        if: success()
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.WORKSPACE }}/node_modules
            ${{ env.WORKSPACE }}/.nuxt
          key: ci-cache-node-${{ hashFiles('v-poc/ci/cache-node/package-lock.json') }}
