name: collector-gin

on:
  push:
    paths:
      - 'v-demo/collector/collector-gin/**'

jobs:
  shortlink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: v-demo/collector/collector-gin
          file: v-demo/collector/collector-gin/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/vitamin.collector-gin:latest
  