name: collection-gin

on:
  push:
    paths:
      - 'v-poc/collection-sdk/s-gin/**'

env:
  COLLECTOR_GIN_PATH: 'v-poc/collection-sdk/s-gin'
  IMAGE_NAME: 'ghcr.io/lkzc19/poc.collection-gin'

jobs:
  collection-gin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.COLLECTOR_GIN_PATH }}
          file: ${{ env.COLLECTOR_GIN_PATH }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
  