name: demo-fs-nuxt

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-demo/demo-fs/fs-nuxt/**'

env:
  WORKSPACE: 'v-demo/demo-fs/fs-nuxt'
  IMAGE_NAME: 'ghcr.io/lkzc19/demo-fs-nuxt'

jobs:
  fs-nuxt-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: NPM
        run: |
          cd ${{ env.WORKSPACE }}
          npm install
          npm run build
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKSPACE }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
  fs-nuxt-notify:
    needs: fs-nuxt-build
    runs-on: ubuntu-latest
    steps:
      - name: Build Notify
        run: |
          curl https://api.day.app/${{ secrets.BARK_PUSH_KEY }}/vitamin/%5Bdemo-fs-nuxt%5D打包成功