name: demo-wx-gin

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-demo/demo-wx/demo-wx-gin/**'

env:
  WORKSPACE: 'v-demo/demo-wx/demo-wx-gin'
  IMAGE_NAME: 'ghcr.io/lkzc19/demo-wx-gin'

jobs:
  sl-spring-bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up go 1.22.5'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5' # The Go version to download (if necessary) and use.
      - name: 'Build'
        run: |
          cd ${{ env.WORKSPACE }}
          go mod tidy
          go build -o app main.go
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKSPACE }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
  