name: demo-wx-gin

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-demo/demo-wx/wx-gin/**'

env:
  WORKSPACE: 'v-demo/demo-wx/wx-gin'
  IMAGE_NAME: 'ghcr.io/lkzc19/demo-wx-gin'

jobs:
  wx-gin-bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKSPACE }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
  wx-gin-notify:
    needs: wx-gin-bulid
    runs-on: ubuntu-latest
    steps:
      - name: Build Notify
        run: |
          curl https://api.day.app/${{ secrets.BARK_PUSH_KEY }}/vitamin/%5Bdemo-wx-gin%5D打包成功