name: shortlink-spring

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-demo/shortlink/shortlink-spring/**'

env:
  PROJECT_PATH: 'v-demo/shortlink/shortlink-spring'
  IMAGE_NAME: 'ghcr.io/lkzc19/demo.shortlink-spring'

jobs:
  shortlink-spring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Package gradle project'
        run: |
          cd ${{ env.PROJECT_PATH }}
          ./gradlew bootJar
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.PROJECT_PATH }}
          file: ${{ env.PROJECT_PATH }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
  