name: shortlink-spring

on:
  push:
    paths:
      - 'v-demo/shortlink/shortlink-spring/**'

jobs:
  shortlink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Package gradle project'
        run: |
          cd v-demo/shortlink/shortlink-spring
          ./gradlew bootJar
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: v-demo/shortlink/shortlink-spring
          file: v-demo/shortlink/shortlink-spring/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/vitamin.shortlink.spring:latest
  